apiVersion: batch/v1
kind: Job
metadata:
  name: merge-reports
  namespace: playwright
  labels:
    RUNID: run-1746112294

spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: merge
        image: mcr.microsoft.com/playwright:v1.52.0-noble
        command: ["/bin/sh", "-c"]
        args:
          - |
            #npx playwright merge-reports /results/*/*/test-results.json --reporter html;
            npx playwright merge-reports /results/${RUN_ID}/*/report.json --reporter html
            cp -r playwright-report /results/${RUN_ID}/final
            sleep 30000
        env:
        - name: RUN_ID
          value: run-1746112294
        volumeMounts:
        - name: results
          mountPath: /results
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: results-pvc
