apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-run-1746292844
  namespace: playwright
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
  # annotations:
  #   "argocd.argoproj.io/hook": PreSync # This should help recreate the job
  #   "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  ttlSecondsAfterFinished: 60  # Keep the Job object for 1 minutes (60 seconds) after completion
  template:
    spec:
      containers:
      - name: playwright
        image: saifb/playwright-test:0.0.3
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/config/entrypoint.sh"]
        env:
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: TOTAL_SHARDS
          value: "3"
        - name: ENVIRONMENT
          value: "stage" # Can be overridden to dev/stage/preprod
        - name: BASE_URL
          value: "https://playwright.dev"
        - name: RUN_ID
          value: run-1746292844
        volumeMounts:
        - name: local-results
          mountPath: /results
        - name: entrypoint-volume
          mountPath: /config
      restartPolicy: Never
      volumes:
      - name: entrypoint-volume
        configMap:
          name: playwright-entrypoint
      - name: local-results
        persistentVolumeClaim:
          claimName: results-pvc
