apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-__RUN_ID__
  namespace: playwright
  # annotations:
  #   "argocd.argoproj.io/hook": PreSync # This should help recreate the job
  #   "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  completions: 4
  parallelism: 4
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: playwright
        image: saifb/playwright-test:0.0.2
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/config/entrypoint.sh"]
        env:
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: TOTAL_SHARDS
          value: "4"
        - name: ENVIRONMENT
          value: "stage" # Can be overridden to dev/stage/preprod
        - name: BASE_URL
          value: "https://playwright.dev"
        - name: RUN_ID
          value: __RUN_ID__
        volumeMounts:
        - name: local-results
          mountPath: /results
        - name: entrypoint-volume
          mountPath: /config
      restartPolicy: Never
      volumes:
      - name: entrypoint-volume
        configMap:
          name: playwright-entrypoint
      - name: local-results
        persistentVolumeClaim:
          claimName: results-pvc
